### ISSUE TITLE
I can't create a contract on the mainnet

### ISSUE THREAD

**Issue by liusDong** [cube-network/Cube#21]
I can create a contract on the testnet but not on the mainnet, I have more than 1000 cubes on the mainnet so it's not a gas problem, I even tested an empty contract on bscmainnet bsctestnet fantom fantomtest cubetestnet all works but It's not works on the cube mainnet

pragma solidity ^0.8.0;
contract EmptyContract{
    fallback() external payable {
    }
}

**Comment by liusDong** [comment]
I have tested deploy contract both with remix and hardhat, and the errors are all {"value":{"code":-32603,"data":{"code":-32000,"message":"unexpected error"}}}
I try all rpc I konw
https://http-mainnet.cube.network
https://http-mainnet-sg.cube.network 
https://http-mainnet-us.cube.network
I also tried the local full node, still invalid

**Comment by Nanyan** [comment]
Please refer to the [Cube Chain Application Form](https://docs.google.com/forms/d/e/1FAIpQLSdNv-LWkj_RW75SHQl2B5rQjdk-ArE_HIfCPd9qc_LcIPUNmQ/viewform).

Thank you for your interests with CUBE Chain.
